### PR TITLE
I have completed the work please review it.

### PR DESCRIPTION
**Pull request by harsh-9389**

### CODE REVIEW

**Comment by harsh-9389** [comment]
I have modified the files you can review it and merge to your main branch.

**Comment by praveen4star** [comment]
Hi @harsh-9389,
   Thanks for your interest in our project.
But We have already written backend code. Right now, I am focusing on UI for login and sign-up and You can raise a PR in dashboard branch.
Feel free to ask your doubt.

**Comment by harsh-9389** [comment]
are you still working on this

**Comment by praveen4star** [comment]
not yet

**Pull request closed without merging**
